const COLOR_RED = "R";
const COLOR_BLUE = "B";
const COLOR_GREEN = "G";
const COLOR_YELLOW = "Y";
const COLOR_ORANGE = "O";
const COLOR_WHITE = "W";
const COLOR_BLACK = "X";

// module.exports = {
//   COLOR_RED: COLOR_RED,
//   COLOR_BLUE: COLOR_BLUE,
//   COLOR_GREEN: COLOR_GREEN,
//   COLOR_YELLOW: COLOR_YELLOW,
//   COLOR_ORANGE: COLOR_ORANGE,
//   COLOR_WHITE: COLOR_WHITE,
//   COLOR_BLACK: COLOR_BLACK
// };
/*
const COLOR_RED = "#FF0000";
const COLOR_BLUE = "#0000FF";
const COLOR_GREEN = "#00FF00";
const COLOR_YELLOW = "#FFFF00";
const COLOR_ORANGE = "#FFA500";
const COLOR_WHITE = "#FFFFFF";
const COLOR_BLACK = "#333333";*/